version: '3.7'

services: 
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:433
    volumes: 
        - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - kibana
    networks:
      - elk
  elasticsearch:
    build: 
      context: elasticsearch/
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes: 
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    networks: 
      - elk
    environment: 
      ES_JAVE_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: "changeme"
      discovery.type: single-node
  logstash:
    build: 
      context: logstash/
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    volumes: 
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports: 
      - 12345:12345/udp
    environment: 
      LS_JAVE_OPTS: "-Xmx256m -Xms256m"
    networks: 
      - elk
    depends_on: 
      - elasticsearch
  kibana:
    build: 
      context: kibana/
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    environment: 
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    volumes: 
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks: 
      - elk
    depends_on: 
      - elasticsearch

networks: 
  elk:
    driver: bridge
    name: elk

volumes: 
  elasticsearch:
